---
- name: Install NTP and configure servers
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install NTP package
      apt:
        name: ntp
        state: present

    - name: Add NTP servers to configuration file
      lineinfile:
        path: /etc/ntp.conf
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "server 123.176.37.249 prefer iburst"
        - "server 123.176.40.175 prefer iburst"

